In [1]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch
import numpy as np


In [18]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.FloatTensor(3, 4, 5)
a

tensor([[[1.9725e+33, 4.5741e-41, 1.8077e-43, 0.0000e+00, 2.3697e+18],
         [4.5743e-41, 2.3697e+18, 4.5743e-41, 4.4842e-44, 0.0000e+00],
         [4.4842e-44, 0.0000e+00, 3.2937e-34, 0.0000e+00, 1.1484e+18],
         [4.5743e-41, 8.9683e-44, 0.0000e+00, 4.4842e-44, 0.0000e+00]],

        [[3.2938e-34, 0.0000e+00, 1.1484e+18, 4.5743e-41, 1.3452e-43],
         [0.0000e+00, 4.4842e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.1484e+18, 4.5743e-41, 2.4663e-43, 0.0000e+00, 8.9683e-44],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.1484e+18, 4.5743e-41]],

        [[1.9547e+33, 4.5741e-41, 1.1484e+18, 4.5743e-41, 1.9547e+33],
         [4.5741e-41, 1.1484e+18, 4.5743e-41, 3.3631e-43, 0.0000e+00],
         [1.7937e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.1484e+18],
         [4.5743e-41, 1.9545e+33, 4.5741e-41, 1.1484e+18, 4.5743e-41]]])

In [6]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [8]:
# Приведите его к форме 6х10
a = a.reshape(6, 10)
a

tensor([[1.1439e+18, 4.5743e-41, 3.9212e+08, 4.5743e-41, 1.3783e+18, 4.5743e-41,
         3.9030e+08, 4.5743e-41, 1.3283e+18, 4.5743e-41],
        [1.3288e+18, 4.5743e-41, 1.3674e+18, 4.5743e-41, 3.9305e+08, 4.5743e-41,
         3.9215e+08, 4.5743e-41, 3.9305e+08, 4.5743e-41],
        [9.6933e+07, 4.5743e-41, 1.3283e+18, 4.5743e-41, 1.0645e+18, 4.5743e-41,
         1.0489e+18, 4.5743e-41, 3.9427e+08, 4.5743e-41],
        [3.9427e+08, 4.5743e-41, 1.3306e+18, 4.5743e-41, 1.0428e+17, 4.5743e-41,
         1.3290e+18, 4.5743e-41, 3.9308e+08, 4.5743e-41],
        [1.0679e+09, 4.5743e-41, 3.9032e+08, 4.5743e-41, 1.2882e+18, 4.5743e-41,
         2.6272e+17, 4.5743e-41, 4.1740e+17, 4.5743e-41],
        [3.9430e+08, 4.5743e-41, 3.9308e+08, 4.5743e-41, 1.2468e+18, 4.5743e-41,
         1.3538e+18, 4.5743e-41, 3.9032e+08, 4.5743e-41]])

In [9]:
a.shape

torch.Size([6, 10])

In [11]:
# Создайте случайный IntTensor размера 10
b = torch.IntTensor(10)
b

tensor([2070928920,      32642,  130307062,          0, 2070928920,      32642,
        2070928920,      32642,          0,          0], dtype=torch.int32)

In [19]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
c = a * b
c

RuntimeError: ignored