In [ ]:
!pip install torch

In [18]:
import torch
import numpy as np

In [19]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.FloatTensor(3, 4, 5)
a

tensor([[[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31, 7.2708e+31],
         [5.0778e+31, 3.2608e-12, 1.7728e+28, 7.0367e+22, 2.1715e-18],
         [4.1722e-08, 6.7127e-07, 8.3023e-10, 8.3092e+20, 1.9970e+20],
         [1.0026e-11, 6.4105e-10, 5.2435e-08, 1.6708e-07, 2.1707e-18]],

        [[7.1450e+31, 6.1970e-04, 2.8909e+26, 9.6324e-40, 4.0357e-43],
         [0.0000e+00, 2.9287e-43, 0.0000e+00, 6.7224e-34, 0.0000e+00],
         [1.7616e+01, 4.5628e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 4.5628e-41, 2.7340e+20, 6.8589e+22]],

        [[1.5766e-19, 1.4600e-19, 4.8604e+30, 1.7469e+19, 3.0958e-18],
         [1.0558e-05, 2.1707e-18, 1.9210e+31, 1.7703e+31, 7.6814e+31],
         [2.3316e-09, 1.4587e-19, 7.2708e+31, 7.1430e+31, 1.5766e-19],
         [7.0295e+28, 1.6312e+19, 7.0976e+22, 1.8609e+34, 1.8315e+25]]])

In [20]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [21]:
# Приведите его к форме 6х10
a = a.reshape(6, 10)
a

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31, 7.2708e+31, 5.0778e+31,
         3.2608e-12, 1.7728e+28, 7.0367e+22, 2.1715e-18],
        [4.1722e-08, 6.7127e-07, 8.3023e-10, 8.3092e+20, 1.9970e+20, 1.0026e-11,
         6.4105e-10, 5.2435e-08, 1.6708e-07, 2.1707e-18],
        [7.1450e+31, 6.1970e-04, 2.8909e+26, 9.6324e-40, 4.0357e-43, 0.0000e+00,
         2.9287e-43, 0.0000e+00, 6.7224e-34, 0.0000e+00],
        [1.7616e+01, 4.5628e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 4.5628e-41, 2.7340e+20, 6.8589e+22],
        [1.5766e-19, 1.4600e-19, 4.8604e+30, 1.7469e+19, 3.0958e-18, 1.0558e-05,
         2.1707e-18, 1.9210e+31, 1.7703e+31, 7.6814e+31],
        [2.3316e-09, 1.4587e-19, 7.2708e+31, 7.1430e+31, 1.5766e-19, 7.0295e+28,
         1.6312e+19, 7.0976e+22, 1.8609e+34, 1.8315e+25]])

In [22]:
a.shape

torch.Size([6, 10])

In [23]:
# Создайте случайный IntTensor размера 10
b = torch.IntTensor(10)
b

tensor([140275776,         0, 139614464,         0,        32,         0,
               48,         0, 139615696,         0], dtype=torch.int32)

In [24]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
c = a * b
c

tensor([[3.0450e-10, 0.0000e+00, 2.4779e+36, 0.0000e+00, 2.3267e+33, 0.0000e+00,
         1.5652e-10, 0.0000e+00, 9.8243e+30, 0.0000e+00],
        [5.8525e+00, 0.0000e+00, 1.1591e-01, 0.0000e+00, 6.3904e+21, 0.0000e+00,
         3.0771e-08, 0.0000e+00, 2.3327e+01, 0.0000e+00],
        [       inf, 0.0000e+00, 4.0362e+34, 0.0000e+00, 1.2914e-41, 0.0000e+00,
         1.4058e-41, 0.0000e+00, 9.3855e-26, 0.0000e+00],
        [2.4710e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 3.8171e+28, 0.0000e+00],
        [2.2116e-11, 0.0000e+00,        inf, 0.0000e+00, 9.9066e-17, 0.0000e+00,
         1.0420e-16, 0.0000e+00,        inf, 0.0000e+00],
        [3.2707e-01, 0.0000e+00,        inf, 0.0000e+00, 5.0452e-18, 0.0000e+00,
         7.8300e+20, 0.0000e+00,        inf, 0.0000e+00]])

In [25]:
# либо
c = a.mul(b)
c

tensor([[3.0450e-10, 0.0000e+00, 2.4779e+36, 0.0000e+00, 2.3267e+33, 0.0000e+00,
         1.5652e-10, 0.0000e+00, 9.8243e+30, 0.0000e+00],
        [5.8525e+00, 0.0000e+00, 1.1591e-01, 0.0000e+00, 6.3904e+21, 0.0000e+00,
         3.0771e-08, 0.0000e+00, 2.3327e+01, 0.0000e+00],
        [       inf, 0.0000e+00, 4.0362e+34, 0.0000e+00, 1.2914e-41, 0.0000e+00,
         1.4058e-41, 0.0000e+00, 9.3855e-26, 0.0000e+00],
        [2.4710e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 3.8171e+28, 0.0000e+00],
        [2.2116e-11, 0.0000e+00,        inf, 0.0000e+00, 9.9066e-17, 0.0000e+00,
         1.0420e-16, 0.0000e+00,        inf, 0.0000e+00],
        [3.2707e-01, 0.0000e+00,        inf, 0.0000e+00, 5.0452e-18, 0.0000e+00,
         7.8300e+20, 0.0000e+00,        inf, 0.0000e+00]])

In [26]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
d = a.matmul(a.T)
d

tensor([[       inf,        inf,        inf,        inf,        inf,        inf],
        [       inf,        inf, 2.9810e+24, 4.5679e+13,        inf,        inf],
        [       inf, 2.9810e+24,        inf, 1.2586e+33,        inf,        inf],
        [       inf, 4.5679e+13, 1.2586e+33,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf,        inf,        inf]])

In [35]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

y = x**3 + z - 75*t
y.backward()

print('∂(y)/∂(x) =', x.grad.item())
print('∂(y)/∂(z) =', z.grad.item())
print('∂(y)/∂(t) =', t.grad.item())

∂(y)/∂(x) = 3.0
∂(y)/∂(z) = 1.0
∂(y)/∂(t) = -75.0


In [30]:
# Создайте единичный тензор размера 5x6
z = torch.ones(5, 6)
z

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [31]:
type(z)

torch.Tensor

In [32]:
# Переведите его в формат numpy
numpy_arr = z.numpy()
numpy_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [33]:
type(numpy_arr)

numpy.ndarray