In [1]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch
import numpy as np


In [3]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.FloatTensor(3, 4, 5)
a

tensor([[[-1.3255e-04,  4.5647e-41,  9.1888e-35,  0.0000e+00,  9.1915e-35],
         [ 0.0000e+00,  7.2868e-44,  0.0000e+00,  9.1913e-35,  0.0000e+00],
         [ 1.5877e-42,  2.4102e-43,  9.1915e-35,  0.0000e+00,  7.2868e-44],
         [ 4.5646e-41,  9.1913e-35,  0.0000e+00,  1.5891e-42,  0.0000e+00]],

        [[ 9.1915e-35,  0.0000e+00,  7.2868e-44,  2.4102e-43,  9.1914e-35],
         [ 0.0000e+00,  1.5905e-42,  4.5647e-41,  9.1915e-35,  0.0000e+00],
         [ 7.2868e-44,  2.2575e+15,  9.1914e-35,  0.0000e+00,  1.5961e-42],
         [ 2.4102e-43,  9.1915e-35,  0.0000e+00,  7.2868e-44,  0.0000e+00]],

        [[ 9.1914e-35,  0.0000e+00,  3.3631e-44,  0.0000e+00, -7.4000e-05],
         [ 4.5647e-41,  1.4013e-45,  0.0000e+00,  9.1906e-35,  0.0000e+00],
         [ 5.6052e-45,  1.1210e-43,  5.6052e-45,  1.1911e-43,  3.3631e-44],
         [ 0.0000e+00, -1.1128e+17,  4.5646e-41,  1.4013e-45,  4.5646e-41]]])

In [4]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6х10
a = a.reshape(6, 10)
a

tensor([[-1.3255e-04,  4.5647e-41,  9.1888e-35,  0.0000e+00,  9.1915e-35,
          0.0000e+00,  7.2868e-44,  0.0000e+00,  9.1913e-35,  0.0000e+00],
        [ 1.5877e-42,  2.4102e-43,  9.1915e-35,  0.0000e+00,  7.2868e-44,
          4.5646e-41,  9.1913e-35,  0.0000e+00,  1.5891e-42,  0.0000e+00],
        [ 9.1915e-35,  0.0000e+00,  7.2868e-44,  2.4102e-43,  9.1914e-35,
          0.0000e+00,  1.5905e-42,  4.5647e-41,  9.1915e-35,  0.0000e+00],
        [ 7.2868e-44,  2.2575e+15,  9.1914e-35,  0.0000e+00,  1.5961e-42,
          2.4102e-43,  9.1915e-35,  0.0000e+00,  7.2868e-44,  0.0000e+00],
        [ 9.1914e-35,  0.0000e+00,  3.3631e-44,  0.0000e+00, -7.4000e-05,
          4.5647e-41,  1.4013e-45,  0.0000e+00,  9.1906e-35,  0.0000e+00],
        [ 5.6052e-45,  1.1210e-43,  5.6052e-45,  1.1911e-43,  3.3631e-44,
          0.0000e+00, -1.1128e+17,  4.5646e-41,  1.4013e-45,  4.5646e-41]])

In [6]:
a.shape

torch.Size([6, 10])

In [7]:
# Создайте случайный IntTensor размера 10
b = torch.IntTensor(10)
b

tensor([117639008,         0, 117641648,         0,     65537,  16842753,
         16842753,  16842753,  16842753,     65537], dtype=torch.int32)

In [8]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
c = a * b
c

tensor([[-1.5593e+04,  0.0000e+00,  1.0810e-26,  0.0000e+00,  6.0238e-30,
          0.0000e+00,  1.2273e-36,  0.0000e+00,  1.5481e-27,  0.0000e+00],
        [ 1.8677e-34,  0.0000e+00,  1.0813e-26,  0.0000e+00,  4.7755e-39,
          7.6880e-34,  1.5481e-27,  0.0000e+00,  2.6764e-35,  0.0000e+00],
        [ 1.0813e-26,  0.0000e+00,  8.5723e-36,  0.0000e+00,  6.0237e-30,
          0.0000e+00,  2.6788e-35,  7.6883e-34,  1.5481e-27,  0.0000e+00],
        [ 8.5721e-36,  0.0000e+00,  1.0813e-26,  0.0000e+00,  1.0460e-37,
          4.0595e-36,  1.5481e-27,  0.0000e+00,  1.2273e-36,  0.0000e+00],
        [ 1.0813e-26,  0.0000e+00,  3.9564e-36,  0.0000e+00, -4.8498e+00,
          7.6883e-34,  2.3602e-38,  0.0000e+00,  1.5479e-27,  0.0000e+00],
        [ 6.5939e-37,  0.0000e+00,  6.5940e-37,  0.0000e+00,  2.2041e-39,
          0.0000e+00, -1.8742e+24,  7.6880e-34,  2.3602e-38,  2.9915e-36]])

In [14]:
# либо
c = a.mul(b)
c

tensor([[-1.5593e+04,  0.0000e+00,  1.0810e-26,  0.0000e+00,  6.0238e-30,
          0.0000e+00,  1.2273e-36,  0.0000e+00,  1.5481e-27,  0.0000e+00],
        [ 1.8677e-34,  0.0000e+00,  1.0813e-26,  0.0000e+00,  4.7755e-39,
          7.6880e-34,  1.5481e-27,  0.0000e+00,  2.6764e-35,  0.0000e+00],
        [ 1.0813e-26,  0.0000e+00,  8.5723e-36,  0.0000e+00,  6.0237e-30,
          0.0000e+00,  2.6788e-35,  7.6883e-34,  1.5481e-27,  0.0000e+00],
        [ 8.5721e-36,  0.0000e+00,  1.0813e-26,  0.0000e+00,  1.0460e-37,
          4.0595e-36,  1.5481e-27,  0.0000e+00,  1.2273e-36,  0.0000e+00],
        [ 1.0813e-26,  0.0000e+00,  3.9564e-36,  0.0000e+00, -4.8498e+00,
          7.6883e-34,  2.3602e-38,  0.0000e+00,  1.5479e-27,  0.0000e+00],
        [ 6.5939e-37,  0.0000e+00,  6.5940e-37,  0.0000e+00,  2.2041e-39,
          0.0000e+00, -1.8742e+24,  7.6880e-34,  2.3602e-38,  2.9915e-36]])

In [20]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
d = a.matmul(a.T)
d

tensor([[ 1.7568e-08,  0.0000e+00, -1.2183e-38,  1.0305e-25, -1.8985e-38,
         -8.1086e-27],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  5.4411e-28,  0.0000e+00,
         -1.0228e-17],
        [-1.2183e-38,  0.0000e+00,  0.0000e+00,  0.0000e+00, -6.8016e-39,
         -1.7698e-25],
        [ 1.0305e-25,  5.4411e-28,  0.0000e+00,  5.0963e+30,  0.0000e+00,
         -1.0228e-17],
        [-1.8985e-38,  0.0000e+00, -6.8016e-39,  0.0000e+00,  5.4761e-09,
         -1.5593e-28],
        [-8.1086e-27, -1.0228e-17, -1.7698e-25, -1.0228e-17, -1.5593e-28,
          1.2383e+34]])

In [10]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)


In [13]:
# Создайте единичный тензор размера 5x6
z = torch.ones(5, 6)
z

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [22]:
type(z)

torch.Tensor

In [27]:
# Переведите его в формат numpy
numpy_arr = z.numpy()
numpy_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [28]:
type(numpy_arr)

numpy.ndarray